all:
	$(MAKE) -C examples

error-list.xml: ,xproc20.xml
	@echo FIXME: Build error-list.xml from source
#	@echo Extract error list: $@
#	@$(SAXON) -s:$< -xsl:../../style/error-list.xsl -o:$@

clean:
	$(MAKE) -C examples clean
