all:
	$(MAKE) -C xproc11-steps typed-pipeline-library.xml
	$(MAKE) -C xproc11
	$(MAKE) -C xproc11-steps

clean:
	$(MAKE) -C xproc11 clean
	$(MAKE) -C xproc11-steps clean
	$(MAKE) -C ns-c clean
	$(MAKE) -C ns-err clean
	$(MAKE) -C ns-p clean
