all:
	$(MAKE) -C xproc30-steps typed-pipeline-library.xml
	$(MAKE) -C xproc30
	$(MAKE) -C xproc30-steps

clean:
	$(MAKE) -C xproc30 clean
	$(MAKE) -C xproc30-steps clean
	$(MAKE) -C ns-c clean
	$(MAKE) -C ns-err clean
	$(MAKE) -C ns-p clean
